version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: walletx-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: walletx_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: walletx-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: walletx-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/walletx_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_DATA_REDIS_HOST: redis
      JWT_SECRET: walletx-super-secret-key-for-jwt-signing-2024-melvin
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  mysql_data: