# Server
server.port=8080
spring.application.name=walletx

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/walletx_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=melwin22depp
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.org.hibernate.SQL=DEBUG

# JWT
jwt.secret=walletx-super-secret-key-for-jwt-signing-2024-melvin
jwt.expiration=86400000